Issue #446: Fixed calls to open without ctx manager
princeton-nlp/SWE-agent pull request #469
Opened 2024-05-31 04:20 UTC by milaiwi

#### Reference Issues/PRs

Fixes #446 

#### What does this implement/fix? Explain your changes.

Fixes issues identified by Ruff which advises on proper file handling in Python. Replaces direct file handling methods with safer context handler by using `Path.read_text()` and `with open(...) as file:` where appropriate. 

#### Files

1. evaluation/aggregate_results.py
2. evaluation/evaluation.py
3. inspector/server.py
4. make_demos/convert_traj_to_demo.py
5. run_replay.py
6. sweagent/agent/agents.py
7. sweagent/agent/commands.py
8. sweagent/agent/models.py
9. sweagent/environment/swe_env.py
10. sweagent/environment/utils.py
11. inspector/static.py

2024-05-31 19:29 UTC, klieret commented
Just skimmed it and it looks good. Don't mind the build-docs failure, that's probably on me.

Gonna look a bit more thoroughly in a bit!

2024-06-02 00:44 UTC, klieret requested changes

2024-06-02 00:44 UTC, klieret commented on inspector/server.py
> +            data = [json.loads(x) for x in Path(data_path).read_text().splitlines(keepend=True)]
this should be `keepends`

2024-06-02 00:45 UTC, klieret commented on inspector/server.py
> +            data = [json.loads(x) for x in Path(data_path).read_text().splitlines(keepend=True)]
Will merge after this is resolved :)

2024-06-02 15:04 UTC, milaiwi commented on inspector/server.py
> +            data = [json.loads(x) for x in Path(data_path).read_text().splitlines(keepend=True)]
Fixed! :)

2024-06-02 15:35 UTC, ofirpress commented
Thanks @milaiwi !

2024-06-02 17:09 UTC, merged

2024-06-02 17:09 UTC, klieret commented
Thanks!